# Generated by Django 3.0.5 on 2020-04-25 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200426_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 0, 54, 33, 615863)),
        ),
    ]
